development:
  sessions:
    default:
      database: tdd_development
      hosts:
        - localhost:27017
      options:
  options:
    identity_map_enabled: true
test:
  sessions:
    default:
      database: tdd_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
integration:
  sessions:
    default:
      database: tdd_integration
      hosts:
        - localhost:27017
      options:
  options:
    identity_map_enabled: true
release:
  sessions:
    default:
      database: tdd_release
      hosts:
        - localhost:27017
      options:
  options:
    identity_map_enabled: true
production:
  sessions:
    default:
      database: tdd_production
      hosts:
        - localhost:27017
      options:
        safe: true
        consistency: :strong
  options:
    identity_map_enabled: true

